spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/** 
        - id: reservation
          uri: lb://reservation
          predicates:
            - Path=/api/v1/reservations/** 
        - id: payment
          uri: lb://hotelManagement
          predicates:
            - Path=/api/v1/hotelManagements/** 
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/v1/payments/** 
        - id: notification
          uri: lb://notification
          predicates:
            - Path=/api/v1/notifications/** 
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/